apiVersion: apps/v1
kind: Deployment
metadata:
  name: a2-deployment
spec:
  selector:
    matchLabels:
      app: a2
  replicas: 1
  template:
    metadata:
      labels:
        app: a2
    spec:
      containers:
      - name: a2
        image: a2
        imagePullPolicy: Never
        ports:
        - containerPort: 80
